<?php

namespace app\models\auxiliares;

use yii\db\ActiveRecord;

class tipo_inmueble extends ActiveRecord
{
    public static function tableName(): string
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public static function getTipo($id){
        return parent::find()->select('tipo')->where(['id' => $id])->scalar();
    }
}